### ISSUE TITLE
Missing tests in argmin-math

### ISSUE THREAD

**Issue by stefan-k** [argmin-rs/argmin#275]
Some parts of argmin-math are still missing tests. This is an overview-issue to keep track of all missing tests. Implementing these tests may be a good opportunity for potential contributors to get started ;)

### primitives

* [x] [random.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/primitives/random.rs) (#280)
* [x] [l1norm.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/primitives/l1norm.rs) Missing tests for complex types (#288)
* [x] [l2norm.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/primitives/l2norm.rs) Missing tests for complex types (#289)
* [x] [zero.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/primitives/zero.rs) Missing tests for complex types (#290)

### vec backend

* [x] [minmax.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/minmax.rs) (#286)
* [x] [random.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/random.rs) (#281)
* [x] [signum.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/signum.rs) (#284)
* [x] [div.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/div.rs) Missing tests for complex types (#291)
* [x] [dot.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/dot.rs) Missing tests for complex types (#292)
* [x] [l1norm.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/l1norm.rs) Missing tests for complex types (#293)
* [x] [l2norm.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/l2norm.rs) Missing tests for complex types (#294)
* [x] [mul.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/mul.rs) Missing tests for complex types (#299)
* [x] [sub.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/vec/sub.rs) Missing tests for complex types (#301)

### ndarray backend

* [x] [minmax.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/minmax.rs) (#285)
* [x] [random.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/random.rs) (#279)
* [x] [signum.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/signum.rs) (#287)
* [x] [mul.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/mul.rs) Missing tests for complex types (#300)
* [x] [conj.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/conj.rs) Missing tests for Array2 (#302)
* [x] [dot.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/dot.rs) Missing tests for complex types (#297, #298)
* [x] [l1norm.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/l1norm.rs) Missing tests for complex types (#295)
* [x] [l2norm.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/ndarray_m/l2norm.rs) Missing tests for complex types (#296)

### nalgebra backend

* [x] missing an `ArgminRandom` implementation + tests (#273 & #277)
* [x] [inv.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/nalgebra_m/inv.rs) Error path not tested (#304)
* [x] [random.rs](https://github.com/argmin-rs/argmin/blob/main/argmin-math/src/nalgebra_m/random.rs) Test when min/max arrays are switched (#303)

**Comment by stefan-k** [comment]
yay, 100% coverage in argmin-math!
